# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_stringrs_wrappers", use_symbols = TRUE, package_name = "stringrs")

#' @docType package
#' @usage NULL
#' @useDynLib stringrs, .registration = TRUE
NULL

string_detect <- function(s, re) .Call(wrap__string_detect, s, re)


# nolint end
