# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_stringrs_wrappers", use_symbols = TRUE, package_name = "stringrs")

#' @docType _PACKAGE
#' @usage NULL
#' @useDynLib stringrs, .registration = TRUE
NULL

r_string_detect <- function(s, pattern) .Call(wrap__r_string_detect, s, pattern)


# nolint end
